-- SEForge authoritative baseline. All timestamps are persisted in UTC by the application/JDBC session.

CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    email VARCHAR(190) NOT NULL,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    locked BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_users_email (email),
    UNIQUE KEY uk_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE user_profiles (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    account_type VARCHAR(20) NOT NULL,
    student_no VARCHAR(64) NULL,
    teacher_no VARCHAR(64) NULL,
    department VARCHAR(128) NULL,
    avatar_url VARCHAR(500) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_profiles_user (user_id),
    UNIQUE KEY uk_user_profiles_student_no (student_no),
    UNIQUE KEY uk_user_profiles_teacher_no (teacher_no),
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE roles (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    code VARCHAR(32) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_roles_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE user_roles (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_roles_user_role (user_id, role_id),
    KEY idx_user_roles_role (role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO roles (code, name) VALUES ('ADMIN', 'Administrator'), ('USER', 'User');

CREATE TABLE semesters (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(100) NOT NULL,
    starts_on DATE NOT NULL,
    ends_on DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_semesters_code (code),
    KEY idx_semesters_status_dates (status, starts_on, ends_on)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE courses (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(160) NOT NULL,
    description TEXT NULL,
    semester_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_courses_code (code),
    KEY idx_courses_semester_status (semester_id, status),
    KEY idx_courses_owner (owner_id),
    CONSTRAINT fk_courses_semester FOREIGN KEY (semester_id) REFERENCES semesters (id) ON DELETE RESTRICT,
    CONSTRAINT fk_courses_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE course_classes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(120) NOT NULL,
    capacity INT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_course_classes_code (course_id, code),
    KEY idx_course_classes_course (course_id, name),
    CONSTRAINT fk_course_classes_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE course_members (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NOT NULL,
    class_id BIGINT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    joined_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_course_members_user (course_id, user_id),
    KEY idx_course_members_course_role (course_id, role, status),
    KEY idx_course_members_user_status (user_id, status),
    KEY idx_course_members_class (class_id),
    CONSTRAINT fk_course_members_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_members_class FOREIGN KEY (class_id) REFERENCES course_classes (id) ON DELETE SET NULL,
    CONSTRAINT fk_course_members_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE course_invites (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    code VARCHAR(32) NOT NULL,
    course_id BIGINT NOT NULL,
    class_id BIGINT NULL,
    member_role VARCHAR(20) NOT NULL DEFAULT 'STUDENT',
    max_uses INT NULL,
    used_count INT NOT NULL DEFAULT 0,
    expires_at TIMESTAMP(6) NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_course_invites_code (code),
    KEY idx_course_invites_course_active (course_id, active, expires_at),
    KEY idx_course_invites_class (class_id),
    CONSTRAINT fk_course_invites_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_invites_class FOREIGN KEY (class_id) REFERENCES course_classes (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_invites_creator FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE course_chapters (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NOT NULL,
    parent_id BIGINT NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_course_chapters_order (course_id, sort_order, id),
    KEY idx_course_chapters_parent (parent_id),
    CONSTRAINT fk_course_chapters_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_chapters_parent FOREIGN KEY (parent_id) REFERENCES course_chapters (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE knowledge_points (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NOT NULL,
    chapter_id BIGINT NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_knowledge_points_order (course_id, sort_order, id),
    KEY idx_knowledge_points_chapter (chapter_id),
    CONSTRAINT fk_knowledge_points_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_points_chapter FOREIGN KEY (chapter_id) REFERENCES course_chapters (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE course_resources (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NOT NULL,
    chapter_id BIGINT NULL,
    uploader_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    resource_type VARCHAR(20) NOT NULL,
    object_key VARCHAR(512) NOT NULL,
    content_type VARCHAR(150) NULL,
    size_bytes BIGINT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_course_resources_object (object_key),
    KEY idx_course_resources_course_status (course_id, status, created_at),
    KEY idx_course_resources_chapter (chapter_id),
    CONSTRAINT fk_course_resources_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_resources_chapter FOREIGN KEY (chapter_id) REFERENCES course_chapters (id) ON DELETE SET NULL,
    CONSTRAINT fk_course_resources_uploader FOREIGN KEY (uploader_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE course_announcements (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    published_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_course_announcements_course (course_id, published_at),
    CONSTRAINT fk_course_announcements_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_announcements_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE async_job (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    job_type VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL,
    aggregate_type VARCHAR(64) NULL,
    aggregate_id BIGINT NULL,
    course_id BIGINT NULL,
    requested_by BIGINT NULL,
    payload JSON NULL,
    result JSON NULL,
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 3,
    available_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    lease_owner VARCHAR(128) NULL,
    lease_expires_at TIMESTAMP(6) NULL,
    started_at TIMESTAMP(6) NULL,
    completed_at TIMESTAMP(6) NULL,
    error_code VARCHAR(64) NULL,
    error_message TEXT NULL,
    idempotency_key VARCHAR(190) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_async_job_idempotency (idempotency_key),
    KEY idx_async_job_claim (status, available_at, lease_expires_at),
    KEY idx_async_job_course (course_id, job_type, status),
    CONSTRAINT fk_async_job_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_async_job_requester FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE outbox_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    payload JSON NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    attempt_count INT NOT NULL DEFAULT 0,
    available_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    published_at TIMESTAMP(6) NULL,
    last_error TEXT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_outbox_event_publish (status, available_at, id),
    KEY idx_outbox_event_aggregate (aggregate_type, aggregate_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE ai_trace (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NULL,
    user_id BIGINT NULL,
    job_id BIGINT NULL,
    request_id VARCHAR(64) NOT NULL,
    trace_id VARCHAR(64) NOT NULL,
    capability VARCHAR(32) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    prompt_name VARCHAR(128) NULL,
    prompt_version VARCHAR(64) NULL,
    input_tokens INT NULL,
    output_tokens INT NULL,
    latency_ms BIGINT NULL,
    tool_calls JSON NULL,
    status VARCHAR(24) NOT NULL,
    error_code VARCHAR(64) NULL,
    started_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_ai_trace_course_time (course_id, created_at),
    KEY idx_ai_trace_request (request_id),
    KEY idx_ai_trace_job (job_id),
    CONSTRAINT fk_ai_trace_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_trace_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_ai_trace_job FOREIGN KEY (job_id) REFERENCES async_job (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE knowledge_document (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NOT NULL,
    resource_id BIGINT NULL,
    chapter_id BIGINT NULL,
    uploader_id BIGINT NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    object_key VARCHAR(512) NOT NULL,
    media_type VARCHAR(150) NOT NULL,
    size_bytes BIGINT NOT NULL,
    checksum VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL,
    parser_version VARCHAR(64) NOT NULL,
    embedding_version VARCHAR(64) NOT NULL,
    chunking_version VARCHAR(64) NOT NULL,
    last_error TEXT NULL,
    ingested_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_knowledge_document_object (object_key),
    UNIQUE KEY uk_knowledge_document_checksum (course_id, checksum),
    UNIQUE KEY uk_knowledge_document_resource (resource_id),
    KEY idx_knowledge_document_course_status (course_id, status, created_at),
    KEY idx_knowledge_document_chapter (chapter_id),
    CONSTRAINT fk_knowledge_document_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_document_resource FOREIGN KEY (resource_id) REFERENCES course_resources (id) ON DELETE SET NULL,
    CONSTRAINT fk_knowledge_document_chapter FOREIGN KEY (chapter_id) REFERENCES course_chapters (id) ON DELETE SET NULL,
    CONSTRAINT fk_knowledge_document_uploader FOREIGN KEY (uploader_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE ingestion_job (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    async_job_id BIGINT NULL,
    requested_by BIGINT NOT NULL,
    status VARCHAR(24) NOT NULL,
    parser_version VARCHAR(64) NOT NULL,
    embedding_version VARCHAR(64) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    error_code VARCHAR(64) NULL,
    error_message TEXT NULL,
    started_at TIMESTAMP(6) NULL,
    completed_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_ingestion_job_async (async_job_id),
    KEY idx_ingestion_job_document (document_id, created_at),
    KEY idx_ingestion_job_course_status (course_id, status),
    CONSTRAINT fk_ingestion_job_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_ingestion_job_document FOREIGN KEY (document_id) REFERENCES knowledge_document (id) ON DELETE CASCADE,
    CONSTRAINT fk_ingestion_job_async FOREIGN KEY (async_job_id) REFERENCES async_job (id) ON DELETE SET NULL,
    CONSTRAINT fk_ingestion_job_requester FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE knowledge_chunk (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    chapter_id BIGINT NULL,
    chunk_index INT NOT NULL,
    content LONGTEXT NOT NULL,
    token_count INT NOT NULL,
    page_no INT NULL,
    section_name VARCHAR(255) NULL,
    source VARCHAR(512) NOT NULL,
    parser_version VARCHAR(64) NOT NULL,
    embedding_version VARCHAR(64) NOT NULL,
    vector_id VARCHAR(190) NOT NULL,
    metadata JSON NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_knowledge_chunk_vector (vector_id),
    UNIQUE KEY uk_knowledge_chunk_version (document_id, chunk_index, embedding_version),
    KEY idx_knowledge_chunk_course_version (course_id, embedding_version),
    KEY idx_knowledge_chunk_chapter (chapter_id),
    CONSTRAINT fk_knowledge_chunk_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_chunk_document FOREIGN KEY (document_id) REFERENCES knowledge_document (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_chunk_chapter FOREIGN KEY (chapter_id) REFERENCES course_chapters (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE conversation (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT NULL,
    summary_through_message_id BIGINT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    last_message_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_conversation_owner_course (owner_id, course_id, updated_at),
    KEY idx_conversation_course_status (course_id, status),
    CONSTRAINT fk_conversation_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_conversation_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE conversation_message (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    conversation_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    author_id BIGINT NULL,
    role VARCHAR(24) NOT NULL,
    content LONGTEXT NOT NULL,
    status VARCHAR(24) NOT NULL,
    client_request_id VARCHAR(64) NULL,
    prompt_tokens INT NULL,
    completion_tokens INT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_conversation_message_request (conversation_id, client_request_id),
    KEY idx_conversation_message_order (conversation_id, id),
    KEY idx_conversation_message_course (course_id, created_at),
    CONSTRAINT fk_conversation_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE,
    CONSTRAINT fk_conversation_message_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_conversation_message_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE message_citation (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    message_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    chunk_id BIGINT NOT NULL,
    ordinal INT NOT NULL,
    label VARCHAR(255) NOT NULL,
    source_title VARCHAR(255) NOT NULL,
    page_number INT NULL,
    chapter VARCHAR(255) NULL,
    section VARCHAR(255) NULL,
    quote_text TEXT NULL,
    relevance_score DECIMAL(8,6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_message_citation_order (message_id, ordinal),
    KEY idx_message_citation_course (course_id, message_id),
    KEY idx_message_citation_chunk (chunk_id),
    CONSTRAINT fk_message_citation_message FOREIGN KEY (message_id) REFERENCES conversation_message (id) ON DELETE CASCADE,
    CONSTRAINT fk_message_citation_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_message_citation_document FOREIGN KEY (document_id) REFERENCES knowledge_document (id) ON DELETE CASCADE,
    CONSTRAINT fk_message_citation_chunk FOREIGN KEY (chunk_id) REFERENCES knowledge_chunk (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE answer_feedback (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    message_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating VARCHAR(20) NOT NULL,
    comment TEXT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_answer_feedback_user (message_id, user_id),
    KEY idx_answer_feedback_course (course_id, created_at),
    CONSTRAINT fk_answer_feedback_message FOREIGN KEY (message_id) REFERENCES conversation_message (id) ON DELETE CASCADE,
    CONSTRAINT fk_answer_feedback_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_answer_feedback_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE assignment (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NOT NULL,
    class_id BIGINT NULL,
    created_by BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description LONGTEXT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    available_at TIMESTAMP(6) NULL,
    due_at TIMESTAMP(6) NULL,
    closed_at TIMESTAMP(6) NULL,
    max_submissions INT NOT NULL DEFAULT 1,
    tutor_policy JSON NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_assignment_course_status (course_id, status, due_at),
    KEY idx_assignment_class (class_id, status),
    CONSTRAINT fk_assignment_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_assignment_class FOREIGN KEY (class_id) REFERENCES course_classes (id) ON DELETE SET NULL,
    CONSTRAINT fk_assignment_creator FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE assignment_question (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    assignment_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    knowledge_point_id BIGINT NULL,
    question_type VARCHAR(32) NOT NULL,
    prompt LONGTEXT NOT NULL,
    options JSON NULL,
    reference_answer LONGTEXT NULL,
    max_score DECIMAL(10,2) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    config JSON NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_assignment_question_order (assignment_id, sort_order, id),
    KEY idx_assignment_question_course (course_id, question_type),
    KEY idx_assignment_question_kp (knowledge_point_id),
    CONSTRAINT fk_assignment_question_assignment FOREIGN KEY (assignment_id) REFERENCES assignment (id) ON DELETE CASCADE,
    CONSTRAINT fk_assignment_question_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_assignment_question_kp FOREIGN KEY (knowledge_point_id) REFERENCES knowledge_points (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE rubric (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    assignment_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    total_score DECIMAL(10,2) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_rubric_assignment (assignment_id),
    CONSTRAINT fk_rubric_assignment FOREIGN KEY (assignment_id) REFERENCES assignment (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE rubric_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    rubric_id BIGINT NOT NULL,
    question_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    max_score DECIMAL(10,2) NOT NULL,
    criteria JSON NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_rubric_item_order (rubric_id, sort_order, id),
    KEY idx_rubric_item_question (question_id),
    CONSTRAINT fk_rubric_item_rubric FOREIGN KEY (rubric_id) REFERENCES rubric (id) ON DELETE CASCADE,
    CONSTRAINT fk_rubric_item_question FOREIGN KEY (question_id) REFERENCES assignment_question (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE submission (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    assignment_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    class_id BIGINT NULL,
    user_id BIGINT NOT NULL,
    attempt_no INT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    submitted_at TIMESTAMP(6) NULL,
    is_late BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_submission_attempt (assignment_id, user_id, attempt_no),
    KEY idx_submission_course_user (course_id, user_id, status),
    KEY idx_submission_assignment_status (assignment_id, status, submitted_at),
    KEY idx_submission_class (class_id, status),
    CONSTRAINT fk_submission_assignment FOREIGN KEY (assignment_id) REFERENCES assignment (id) ON DELETE CASCADE,
    CONSTRAINT fk_submission_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_submission_class FOREIGN KEY (class_id) REFERENCES course_classes (id) ON DELETE SET NULL,
    CONSTRAINT fk_submission_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE submission_answer (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    submission_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    answer_text LONGTEXT NULL,
    answer_data JSON NULL,
    attachment_object_key VARCHAR(512) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_submission_answer_question (submission_id, question_id),
    KEY idx_submission_answer_question (question_id),
    CONSTRAINT fk_submission_answer_submission FOREIGN KEY (submission_id) REFERENCES submission (id) ON DELETE CASCADE,
    CONSTRAINT fk_submission_answer_question FOREIGN KEY (question_id) REFERENCES assignment_question (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE grade (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    submission_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    grader_id BIGINT NULL,
    ai_suggested_score DECIMAL(10,2) NULL,
    final_score DECIMAL(10,2) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    confirmed_at TIMESTAMP(6) NULL,
    override_reason TEXT NULL,
    model_name VARCHAR(128) NULL,
    prompt_version VARCHAR(64) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_grade_submission (submission_id),
    KEY idx_grade_course_status (course_id, status, updated_at),
    KEY idx_grade_student (student_id, course_id),
    CONSTRAINT fk_grade_submission FOREIGN KEY (submission_id) REFERENCES submission (id) ON DELETE CASCADE,
    CONSTRAINT fk_grade_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_grade_student FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_grade_grader FOREIGN KEY (grader_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE feedback (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    grade_id BIGINT NOT NULL,
    rubric_item_id BIGINT NULL,
    author_id BIGINT NULL,
    source VARCHAR(24) NOT NULL,
    content TEXT NOT NULL,
    suggested_score DECIMAL(10,2) NULL,
    final_score DECIMAL(10,2) NULL,
    evidence JSON NULL,
    issue_codes JSON NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_feedback_grade (grade_id, rubric_item_id),
    KEY idx_feedback_author (author_id),
    CONSTRAINT fk_feedback_grade FOREIGN KEY (grade_id) REFERENCES grade (id) ON DELETE CASCADE,
    CONSTRAINT fk_feedback_rubric_item FOREIGN KEY (rubric_item_id) REFERENCES rubric_item (id) ON DELETE SET NULL,
    CONSTRAINT fk_feedback_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tutor_interaction (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NOT NULL,
    assignment_id BIGINT NOT NULL,
    question_id BIGINT NULL,
    submission_id BIGINT NULL,
    user_id BIGINT NOT NULL,
    operation VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL,
    student_input LONGTEXT NULL,
    tutor_response LONGTEXT NULL,
    ai_trace_id BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_tutor_interaction_user (user_id, assignment_id, created_at),
    KEY idx_tutor_interaction_course (course_id, operation, created_at),
    KEY idx_tutor_interaction_trace (ai_trace_id),
    CONSTRAINT fk_tutor_interaction_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_tutor_interaction_assignment FOREIGN KEY (assignment_id) REFERENCES assignment (id) ON DELETE CASCADE,
    CONSTRAINT fk_tutor_interaction_question FOREIGN KEY (question_id) REFERENCES assignment_question (id) ON DELETE SET NULL,
    CONSTRAINT fk_tutor_interaction_submission FOREIGN KEY (submission_id) REFERENCES submission (id) ON DELETE SET NULL,
    CONSTRAINT fk_tutor_interaction_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_tutor_interaction_trace FOREIGN KEY (ai_trace_id) REFERENCES ai_trace (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE review_job (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NOT NULL,
    assignment_id BIGINT NULL,
    submission_id BIGINT NULL,
    document_id BIGINT NULL,
    resource_id BIGINT NULL,
    async_job_id BIGINT NULL,
    requested_by BIGINT NOT NULL,
    review_type VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL,
    object_key VARCHAR(512) NULL,
    config JSON NULL,
    error_code VARCHAR(64) NULL,
    error_message TEXT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_review_job_async (async_job_id),
    KEY idx_review_job_course_status (course_id, review_type, status),
    KEY idx_review_job_submission (submission_id),
    CONSTRAINT fk_review_job_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_job_assignment FOREIGN KEY (assignment_id) REFERENCES assignment (id) ON DELETE SET NULL,
    CONSTRAINT fk_review_job_submission FOREIGN KEY (submission_id) REFERENCES submission (id) ON DELETE SET NULL,
    CONSTRAINT fk_review_job_document FOREIGN KEY (document_id) REFERENCES knowledge_document (id) ON DELETE SET NULL,
    CONSTRAINT fk_review_job_resource FOREIGN KEY (resource_id) REFERENCES course_resources (id) ON DELETE SET NULL,
    CONSTRAINT fk_review_job_async FOREIGN KEY (async_job_id) REFERENCES async_job (id) ON DELETE SET NULL,
    CONSTRAINT fk_review_job_requester FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE review_report (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    review_job_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    status VARCHAR(24) NOT NULL,
    summary LONGTEXT NULL,
    structured_result JSON NOT NULL,
    export_object_key VARCHAR(512) NULL,
    model_name VARCHAR(128) NULL,
    prompt_version VARCHAR(64) NULL,
    generated_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_review_report_job (review_job_id),
    KEY idx_review_report_course (course_id, generated_at),
    CONSTRAINT fk_review_report_job FOREIGN KEY (review_job_id) REFERENCES review_job (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_report_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE analytics_snapshot (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    course_id BIGINT NOT NULL,
    class_id BIGINT NULL,
    metric_type VARCHAR(64) NOT NULL,
    period_start TIMESTAMP(6) NULL,
    period_end TIMESTAMP(6) NOT NULL,
    payload JSON NOT NULL,
    generated_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_analytics_snapshot_period (course_id, class_id, metric_type, period_end),
    KEY idx_analytics_snapshot_course (course_id, metric_type, generated_at),
    CONSTRAINT fk_analytics_snapshot_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_analytics_snapshot_class FOREIGN KEY (class_id) REFERENCES course_classes (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE audit_log (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    actor_id BIGINT NULL,
    course_id BIGINT NULL,
    action VARCHAR(80) NOT NULL,
    target_type VARCHAR(80) NULL,
    target_id BIGINT NULL,
    outcome VARCHAR(24) NOT NULL,
    trace_id VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_audit_log_actor_time (actor_id, occurred_at),
    KEY idx_audit_log_course_time (course_id, occurred_at),
    KEY idx_audit_log_target (target_type, target_id),
    KEY idx_audit_log_trace (trace_id),
    CONSTRAINT fk_audit_log_actor FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_audit_log_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
